### PR TITLE
Use pkg/errors for error stack traces

### LINKED ISSUE #2: Unnecessary dependencies in go.sum and binary
This is not urgent in any way, but thought I would mention it, in my project I have this in my go.mod:
```
require (
	github.com/veandco/go-sdl2 v0.4.24
	github.com/vkngwrapper/core v1.0.5
	github.com/vkngwrapper/extensions v1.0.4
	github.com/vkngwrapper/integrations/sdl2 v1.0.4
)
```

And this results in a huge go.sum of 394 lines including things like "google.golang.org/grpc", "github.com/valyala/fasthttp" and "github.com/coreos/etcd" etc..

Most of these things are not included in my binary, but here is the list of things that are included and it does include some things which seem unnecessary:
```
go list -deps -f '{{define "M"}}{{.Path}}@{{.Version}}{{end}}{{with .Module}}{{if not .Main}}{{if .Replace}}{{template "M" .Replace}}{{else}}{{template "M" .}}{{end}}{{end}}{{end}}' | sort -u
github.com/CannibalVox/cgoparam@v1.0.0
github.com/cockroachdb/errors@v1.9.0
github.com/cockroachdb/logtags@v0.0.0-20211118104740-dabe8e521a4f
github.com/cockroachdb/redact@v1.1.3
github.com/getsentry/sentry-go@v0.13.0
github.com/gogo/protobuf@v1.3.2
github.com/google/uuid@v1.3.0
github.com/kr/pretty@v0.3.0
github.com/kr/text@v0.2.0
github.com/pkg/errors@v0.9.1
github.com/rogpeppe/go-internal@v1.8.1
github.com/veandco/go-sdl2@v0.4.24
github.com/vkngwrapper/core@v1.0.5
github.com/vkngwrapper/extensions@v1.0.4
github.com/vkngwrapper/integrations/sdl2@v1.0.4
golang.org/x/sys@v0.0.0-20220808155132-1c4a2a72c664
```

I think all of this stuff might come from github.com/cockroachdb/errors (?) so maybe that package could be swapped out for something simpler like just the standard errors package https://pkg.go.dev/errors which already provides error wrapping functionality.

### PR DESCRIPTION
**Pull request by mewmew**
Fixes #2.

### CODE REVIEW

File: core1_0/buffer_copy.go [hunk 1]
```diff
@@ -6,9 +6,10 @@ package core1_0
 */
 import "C"
 import (
-	"github.com/CannibalVox/cgoparam"
-	"github.com/cockroachdb/errors"
 	"unsafe"
```
Comment (mewmew) [inline core1_0/buffer_copy.go:9]: The reason imports are re-arranged (i.e. `unsafe` moved to the top) is since [goimports](https://pkg.go.dev/golang.org/x/tools/cmd/goimports) was used to sort imports, and it groups standard library imports away from external imports.

**Review by CannibalVox — APPROVED** [review]
Wow, thank you for the elbow grease! I've been getting increasingly aggravated with cockroachdb/errors as I've been working on vkng's VMA port and I'd been meaning to go back and take care of this. I really appreciate it!

**Comment by mewmew** [comment]
> Wow, thank you for the elbow grease! I've been getting increasingly aggravated with cockroachdb/errors as I've been working on vkng's VMA port and I'd been meaning to go back and take care of this. I really appreciate it!

happy to help : )
